name: Test
on: push
env:
  TEST_TAG: ${{ github.actor }}/asdf:test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          pull: true
          push: false
          tags: ${{ env.TEST_TAG }}
      - name: Test loading asdf script
        run: docker run --rm ${{ env.TEST_TAG }} bash -c 'source /asdf/.asdf/asdf.sh && asdf version'
